### ISSUE TITLE
突然报错不能用了

### ISSUE THREAD

**Issue by Kiana1314** [MinatoAquaCrews/nonebot_plugin_randomtkk#9]
10-23 11:44:40 [INFO] nonebot | Event will be handled by <Matcher from nonebot_plugin_randomtkk.nonebot_plugin_randomtkk, type=message, priority=12, temp=False>

10-23 11:44:40 [INFO] nonebot | Matcher <Matcher from nonebot_plugin_randomtkk.nonebot_plugin_randomtkk, type=message, priority=12, temp=False> running complete
10-23 11:44:40 [ERROR] nonebot | Running matcher <Matcher from nonebot_plugin_randomtkk.nonebot_plugin_randomtkk, type=message, priority=12, temp=False> failed.
Traceback (most recent call last):
  File "C:\bot\NB3\LittlePaimon\bot.py", line 54, in <module>
    nonebot.run(app="__mp_main__:app", access_log=False)
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\__init__.py", line 261, in run
    get_driver().run(*args, **kwargs)
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\drivers\fastapi.py", line 170, in run
    uvicorn.run(
  File "C:\bot\NB3\venv\lib\site-packages\uvicorn\main.py", line 576, in run
    server.run()
  File "C:\bot\NB3\venv\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 633, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 600, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1896, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\message.py", line 146, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\bot\NB3\venv\lib\site-packages\nonebot\message.py", line 196, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\internal\matcher.py", line 672, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\internal\matcher.py", line 639, in simple_run
    await handler(
  File "C:\bot\NB3\venv\lib\site-packages\nonebot\dependencies\__init__.py", line 92, in __call__
    return await self.call(**values)
  File "C:\bot\NB3\LittlePaimon\nonebot_plugin_randomtkk\nonebot_plugin_randomtkk\__init__.py", line 73, in _
    img_file, waiting = random_tkk_handler.one_go(matcher, gid, uid, level, _charac)
  File "C:\bot\NB3\LittlePaimon\nonebot_plugin_randomtkk\nonebot_plugin_randomtkk\handler.py", line 190, in one_go
    img_file, mark_file = self._draw_tkk(row, col, tkk_size, find_charac)
  File "C:\bot\NB3\LittlePaimon\nonebot_plugin_randomtkk\nonebot_plugin_randomtkk\handler.py", line 107, in _draw_tkk
    base2.paste(mark,((row - 1) * 64, (col - 1) * 64), mark)
  File "C:\bot\NB3\venv\lib\site-packages\PIL\Image.py", line 1628, in paste
    self.im.paste(im, box, mask.im)
ValueError: bad transparency mask

**Comment by KafCoppelia** [comment]
重新安装一下PIL

**Comment by Kiana1314** [comment]
Pillow9.2.0
![6a5176fdcd877fd6b46030bd78385552](https://user-images.githubusercontent.com/107671434/198510513-79209fcb-39c2-423b-9a7e-0f666d409cb5.png)
![EFR5BF}M1%2}XP(QKZJ%CSN](https://user-images.githubusercontent.com/107671434/198510542-0f32e9ac-c33a-45dc-83cb-a2c2eae84805.png)

**Comment by zhulinyv** [comment]
> Pillow9.2.0 ![6a5176fdcd877fd6b46030bd78385552](https://user-images.githubusercontent.com/107671434/198510513-79209fcb-39c2-423b-9a7e-0f666d409cb5.png) ![EFR5BF}M1%2}XP(QKZJ%CSN](https://user-images.githubusercontent.com/107671434/198510542-0f32e9ac-c33a-45dc-83cb-a2c2eae84805.png)

I have the same problem.

**Comment by KafCoppelia** [comment]
我在Linux Python 3.9与Windows Python 3.8/3.11下测试均无法复现这个问题，建议反馈到[Pillow](https://github.com/python-pillow/Pillow)吧

**Comment by Ikaros-521** [comment]
同样的问题+1

**Comment by zhulinyv** [comment]
The version 0.15 under the dev branch seems to work fine. ：)

**Comment by KafCoppelia** [comment]
> The version 0.15 under the dev branch seems to work fine. ：)

但是`v0.1.5`并没有改变什么依赖，`Pillow`部分根本没动……

**Comment by zhulinyv** [comment]
> > The version 0.15 under the dev branch seems to work fine. ：)
> 
> 但是`v0.1.5`并没有改变什么依赖，`Pillow`部分根本没动……

That's quite strange, I don't know what happend.

**Comment by Ikaros-521** [comment]
解决方案：
修改handler.py 第107行
```
base2.paste(mark,((row - 1) * 64, (col - 1) * 64))
# base2.paste(mark,((row - 1) * 64, (col - 1) * 64), mark)
```
pull: [https://github.com/MinatoAquaCrews/nonebot_plugin_randomtkk/pull/10](https://github.com/MinatoAquaCrews/nonebot_plugin_randomtkk/pull/10)
